"""
AI Detector

Today's challenge is inspired by the release of ChatGPT on November 30, 2022.

Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:

It contains two or more dashes (-).

It contains two or more sets of parenthesis (()). Text can be within the parenthesis.

It contains three or more words with 7 or more letters.

Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters as part of a word.

If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".
"""


HUMAN = "Human"
AI = 'AI'


def filter_letters(word: str) -> str:
    return "".join([char for char in word if char.isalpha()])


def is_wrapped_in_parenthesis(word: str) -> bool:
    return len(word) >= 2 and word.startswith("(") and word.endswith(")")


def detect_ai(text: str) -> str:
    if text.count("-") >= 2:
        return AI

    # It contains two or more sets of parenthesis (()). Text can be within the parenthesis.
    words = text.split()
    if len([word for word in words if is_wrapped_in_parenthesis(word)]) >= 2:
        return AI

    if len([word for word in words if len(filter_letters(word)) >= 7]) >= 3:
        return AI

    return HUMAN


def main():
    print(detect_ai("The quick brown fox jumped over the lazy dog."))
    print(detect_ai("The hypersonic brown fox - jumped (over) the lazy dog."))
    print(detect_ai("Yes - you're right! I made a mistake there - let me try again."))
    print(detect_ai("The extraordinary students were studying vivaciously."))
    print(detect_ai("The (excited) student was (coding) in the library."))


if __name__ == "__main__":
    main()
